config/routes.rb
PollywogRanchRailsRuby003::Application.routes.draw do
  root 'application#index'
  get '/tadpoles/:id/evolve' => 'tadpoles#evolve', as: :evolve_tadpole
  get '/frogs/:id/tadpoles/new' => 'tadpoles#new', as: :tadpole_new
  
  resources :frogs
  resources :ponds
  resources :tadpoles

  

end

app/models/frog.rb
class Frog < ActiveRecord::Base
  belongs_to :pond
  has_many :tadpoles
end

app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs
  has_many :tadpoles
end

app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/frogs_controller.rb
class FrogsController < ApplicationController
  before_action :set_frog, only: [:show, :edit, :update, :destroy]
  def index
    @frogs = Frog.all
  end 

  def new
    @frog = Frog.new
    @ponds = Pond.all
  end

  def show
  end

  def create
    @frog = Frog.new(frog_params)
    if @frog.save
      redirect_to(@frog)
    end
  end

  def update
    if @frog.update(frog_params)
      redirect_to(@frog)
    end
  end

  def edit
    @ponds = Pond.all
  end

  def destroy
    if @frog.destroy
      redirect_to(frogs_path)
    end
  end

  private

  def set_frog
    @frog = Frog.find(params[:id])
  end

  def frog_params
    params.require(:frog).permit(:name, :color, :pond_id)
  end

end

app/controllers/ponds_controller.rb
class PondsController < ApplicationController
  before_action :set_pond, only: [:show, :edit, :update, :destroy]
 
  def index
    @ponds = Pond.all
  end

  def new
    @pond = Pond.new
  end

  def show
  end

  def create
    @pond = Pond.new(pond_params)
    if @pond.save
      redirect_to(@pond)
    end
  end

  def update
    if @pond.update(pond_params)
      redirect_to(@pond)
    end
  end

  def edit
  end

  def destroy
    if @pond.destroy
      redirect_to(ponds_path)
    end
  end

  private

  def set_pond
    @pond = Pond.find(params[:id])
  end

  def pond_params
    params.require(:pond).permit(:name, :water_type)
  end
end

app/controllers/tadpoles_controller.rb
class TadpolesController < ApplicationController
  before_action :set_tadpole, only: [:show, :edit, :update, :destroy]

  def index
    @tadpoles = Tadpole.all
  end

  def new
    @frog = Frog.find(params[:id])
    @tadpole = Tadpole.new
  end

  def show
  end

  def create
   @frog = Frog.find(params[:tadpole][:frog_id])
    @tadpole = @frog.tadpoles.create(tadpole_params)
    if @tadpole.save
      redirect_to(@tadpole)
    end
  end

  def update
    if @tadpole.update(tadpole_params)
      redirect_to(@tadpole)
    end
  end

  def edit
    @tadpoles = Tadpole.all
  end

  def destroy
    if @tadpole.destroy
      redirect_to(tadpoles_path)
    end
  end

  def evolve
    # @tadpole = Tadpole.find_by(:id => params[:id])
    @tadpole = Tadpole.find(params[:id])
    @frog = Frog.new
    @frog.name = @tadpole.name
    @frog.color = @tadpole.color
    @frog.pond = @tadpole.frog.pond
    if @frog.save && @tadpole.destroy
      redirect_to(@frog)
    end
  end

  private
  def set_tadpole
    @tadpole = Tadpole.find(params[:id])
  end

  def tadpole_params
    params.require(:tadpole).permit(:name, :color, :frog_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frogs_helper.rb
module FrogsHelper
end

app/helpers/ponds_helper.rb
module PondsHelper
end

app/helpers/tadpoles_helper.rb
module TadpolesHelper
end

app/views/application/index.html.erb
<h1>Welcome to Pollywog Ranch</h1>
<p>Please select from the choices above.</p>

app/views/frogs/_form.html.erb
<%= form_for(@frog) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :lives %><br>
    <%= f.collection_select :pond_id, @ponds, :id, :name %>   
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frogs/edit.html.erb
<h1>Edit <%= @frog.name %></h1>

<%= render "form" %>

<%= link_to 'Cancel', @frog %>

app/views/frogs/index.html.erb
<h1>Frogs</h1>
<% @frogs.each do |frog| %>
  <p><%= link_to "#{frog.name}", frog %></p>
<% end %>
<p><%= link_to "Create a new frog", new_frog_path %></p>

app/views/frogs/new.html.erb
<h1>Create a new frog</h1>

<%= render "form" %>

app/views/frogs/show.html.erb
<h1><%= @frog.name %> Frog</h1>
<p>Color: <%= @frog.color %></p>
<p>Lives: <%= link_to "#{@frog.pond.name}", pond_path %></p>
<% unless @frog.tadpoles.empty? %>
  <h2>Children</h2>
  <ol>
    <% @frog.tadpoles.each do |tadpole| %>
      <li><%= link_to "#{tadpole.name}", tadpole %></li>
    <% end %>
  </ol><br>
<% end %>
<p><strong><%= link_to "Create new tadpole baby", tadpole_new_path %></strong></p>

<%= link_to 'Back', frogs_path %> | 
<%= link_to 'Edit', edit_frog_path %> | 
<%= link_to 'Destroy', @frog, :method=>:delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pollywog Ranch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <a href="/ponds">Ponds</a> | 
    <a href="/frogs">Frogs</a> | 
    <a href="/tadpoles">Tadpoles</a>
  </nav>
<%= yield %>

</body>
</html>

app/views/ponds/_form.html.erb
<%= form_for(@pond) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :water_type %><br>
    <%= f.text_field :water_type %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/ponds/edit.html.erb
<h1>Edit <%= @pond.name %></h1>

<%= render "form" %>

<%= link_to 'Cancel', @pond %>

app/views/ponds/index.html.erb
<h1>Ponds</h1>
<% @ponds.each do |pond| %>
  <p><%= link_to "#{pond.name}", pond %></p>
<% end %>
<%= link_to "Create a new pond", new_pond_path %>

app/views/ponds/new.html.erb
<h1>Create a new pond</h1>

<%= render "form" %>

<%= link_to 'Cancel', @pond %>

app/views/ponds/show.html.erb
<h1><%= @pond.name %> Pond</h1>
<p>water type: <%= @pond.water_type %></p>
<p>Resident frogs and their tadpoles:</p>
<ol>
  <% @pond.frogs.each do |frog| %>
    <li><%= link_to "#{frog.name}", frog %>
      <ol>
        <% frog.tadpoles.each do |tadpole| %>
          <li><%= link_to "#{tadpole.name}", tadpole %></li>
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>
<%= link_to 'Back', ponds_path %> | 
<%= link_to 'Edit', edit_pond_path %> | 
<%= link_to 'Destroy', @pond, :method=>:delete %>

app/views/tadpoles/edit.html.erb
<h1>Edit <%= @tadpole.name %></h1>
<form action="/tadpoles/<%= @tadpole.id %>/update" method="post">
  <label for="name">Name</label>
  <input type="text" id="name" name="name" placeholder="<%= @tadpole.name %>">
  <label for="color">Color</label>
  <input type="text" id="color" name="color" placeholder="<%= @tadpole.color %>">
  <input type="submit" value="update">
</form><br>
<a href="/tadpoles">Cancel</a>

app/views/tadpoles/index.html.erb
<h1>Tadpoles</h1>
<% @tadpoles.each do |tadpole| %>
  <p><%= link_to "#{tadpole.name}", tadpole %></p>
<% end %>

app/views/tadpoles/new.html.erb
<h1>Create a new tadpole for <%= @frog.name %></h1>

<%= form_for(@tadpole) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">  
    <%= f.hidden_field :color, :value => @frog.color %>
  </div>

  <div class="field">
    <%= f.hidden_field :frog_id, :value => @frog.id %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>

<% end %>

<%= link_to 'Cancel', @tadpole %>

app/views/tadpoles/show.html.erb
<h1><%= @tadpole.name %> Tadpole</h1>
<p>color: <%= @tadpole.color %></p>
<p>parent: <%= link_to "#{@tadpole.frog.name}", frog_path %></p>
<p>lives: <%= link_to "#{@tadpole.frog.pond.name}", pond_path %></p>
<!-- <p><strong><%#= link_to "Evolve to frog", @tadpole.id.to_s + "/evolve", :controller => "tadpole", :method => "evolve" %></strong></p> -->
<p><strong><%= link_to "Evolve to frog", evolve_tadpole_path %></p></strong>
<%= link_to 'Back', tadpoles_path %> | 
<%= link_to 'Edit', edit_tadpole_path %> | 
<%= link_to 'Destroy', @tadpole, :method=>:delete %>